---

- hosts: dev-desktop
  become: yes
  become_user: root

  roles:

    - role: common
      papertrail_url: "{{ vars_papertrail_url }}"
      collect_metrics_from: "{{ global_collect_metrics_from }}"
      sudo_users: "{{ global_sudo_users + vars_extra_sudo_users }}"
      allow_ssh_extra_groups: dev-desktop-allow-ssh

    - role: dev-desktop

  tasks:
    - name: Remove Datadog agent
      apt:
        name: datadog-agent
        state: absent
