[package]
name = "free_disk_space"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.5.1", features = ["derive"] }
walkdir = "2.4.0"

[dev-dependencies]
tempfile = "3.10.0"
